### ISSUE TITLE
Implement retries on queued request

### ISSUE THREAD

**Issue by MarcoBeerepoot** [Cobster/BoardGamer.BoardGameGeek#54]
Nice work! I took a quick look at the code, but I don't think you've implemented this.
When a user has a big collection, requests might be queued when requesting the /collection path.
See https://boardgamegeek.com/thread/1188687/export-collections-has-been-updated-xmlapi-develop

It would be nice if the library checks for a 202 statuscode and retries x attempts after y seconds (defined by consumer or default) until a 200 is received.

**Comment by Cobster** [comment]
@MarcoBeerepoot Apologies on the delayed response...busy week.  I'll get added soon.

**Comment by Cobster** [comment]
@MarcoBeerepoot I did a little digging, and your requested enhancement is already implemented.  This is currently hardcoded to 20 retries with a 500ms delay between requests.  I will make an update to make these values configurable, as I suspect very large collections could take more than 10s to be retrieved.

https://github.com/Cobster/BoardGamer.BoardGameGeek/blob/faf787930d718b784365303cef6a96744155f4b6/src/BoardGamer.BoardGameGeek/BoardGameGeekXmlApi2/BoardGameGeekXmlApi2Client.cs#L974-L994

**Comment by MarcoBeerepoot** [comment]
Apologies, I hadn't seen that. Thanks for commenting :)

**Comment by Cobster** [comment]
No problem @MarcoBeerepoot, I didn't remember if I had ever completed that so it was a good reminder.  The new package v0.7.2 on nuget has been updated with configurable retry options, also added some information to the readme in relation to the game collection retrieval.  I hope this helps you out.
