### ISSUE TITLE
Multiple constructors accepting all given argument types have been found

### ISSUE THREAD

**Issue by tkapusta** [Cobster/BoardGamer.BoardGameGeek#58]
Error:
`"Multiple constructors accepting all given argument types have been found in type 'BoardGamer.BoardGameGeek.BoardGameGeekXmlApi2.BoardGameGeekXmlApi2Client'. There should only be one applicable constructor."`

**Comment by Cobster** [comment]
This appears to stem from dependency injection registration, which is demonstrated in the README.  I appreciate the PR, but the change removes the default options.

I would recommend updating your DI registration to the following, which manually chooses the constructor via factory method:
```
services.AddHttpClient<IBoardGameGeekXmlApi2Client, BoardGameGeekXmlApi2Client>((httpClient) => new BoardGameGeekXmlApi2Client(httpClient));
```

**Comment by tkapusta** [comment]
The README says that:
`services.AddHttpClient<IBoardGameGeekXmlApi2Client, BoardGameGeekXmlApi2Client>();` 
and it doesn't work, so you should update it ;)

Morover - the change does not remove the default option. 
` public BoardGameGeekXmlApi2Client(HttpClient http, BoardGameGeekXmlApi2ClientOptions options = null)`
So the options parameter is optional, if you won't pass it, it will be set to BoardGameGeekXmlApi2ClientOptions.Default

**Comment by Cobster** [comment]
I didn't look closely enough @gosukretess, I see the 2nd constructor already checks for null options and uses the Default.  I will accept the PR and get it merged.

**Comment by Cobster** [comment]
And thank you for the contribution @gosukretess !!

**Comment by tkapusta** [comment]
Thank you for the great library!

**Comment by Cobster** [comment]
@gosukretess I just pushed v0.8.1 to Nuget, so it should be available shortly.
